[config]

[config.wallpaper]
set = true
command = """
awww img {{ image }} --transition-type random --transition-duration 1.4 --transition-fps 60
"""

[templates.wayle]
input_path = "~/.config/matugen/templates/wayle.toml"
output_path = "~/.config/wayle/matugen/colors.toml"

[templates.ghostty]
input_path = "~/.config/matugen/templates/ghostty"
output_path = "~/.config/ghostty/themes/Matugen"

[templates.ghostty-css]
input_path = "~/.config/matugen/templates/ghostty.css"
output_path = "~/.config/ghostty/Matugen.css"
post_hook = "pkill -SIGUSR2 ghostty"

[templates.zed]
input_path = '~/.config/matugen/templates/zed.json'
output_path = '~/.config/zed/themes/matugen.json'
