[styling.palette]
primary = "#c5cc7a"
fg = "#e5e3d6"
fg-muted = "#c8c7b7"
elevated = "#13140c"
surface = "#13140c"
bg = "#13140c"

[modules.dashboard]
icon-color = "#13140c"
icon-bg-color = "#c5cc7a"

[modules.hyprland-workspaces]
container-bg-color = "#13140c"
active-color = "#c5cc7a"

[modules.systray]
button-bg-color = "#13140c"

[modules.clock]
label-color = "#c5cc7a"
button-bg-color = "#13140c"
icon-color = "#13140c"
icon-bg-color = "#c5cc7a"

[modules.world-clock]
label-color = "#a3d0c0"
button-bg-color = "#13140c"
icon-color = "#13140c"
icon-bg-color = "#c5cc7a"

[modules.battery]
label-color = "#c5cc7a"
button-bg-color = "#13140c"
icon-color = "#13140c"
icon-bg-color = "#c5cc7a"

[modules.bluetooth]
label-color = "#c5cc7a"
button-bg-color = "#13140c"
icon-color = "#13140c"
icon-bg-color = "#c5cc7a"

[modules.network]
label-color = "#a3d0c0"
button-bg-color = "#13140c"
icon-color = "#13140c"
icon-bg-color = "#c5cc7a"

[modules.volume]
label-color = "#c5cc7a"
button-bg-color = "#13140c"
icon-color = "#13140c"
icon-bg-color = "#c5cc7a"

[modules.microphone]
label-color = "#c5cc7a"
button-bg-color = "#13140c"
icon-color = "#13140c"
icon-bg-color = "#c5cc7a"

[modules.media]
label-color = "#c5cc7a"
button-bg-color = "#13140c"
icon-color = "#13140c"
icon-bg-color = "#c5cc7a"

[modules.weather]
label-color = "#a3d0c0"
button-bg-color = "#13140c"
icon-color = "#13140c"
icon-bg-color = "#c5cc7a"

[modules.notification]
label-color = "#c5cc7a"
button-bg-color = "#13140c"
icon-color = "#13140c"
icon-bg-color = "#c5cc7a"

[modules.window-title]
label-color = "#c5cc7a"
button-bg-color = "#13140c"
icon-color = "#13140c"
icon-bg-color = "#c5cc7a"

